'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:2.0.50727.5485
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  强类型资源类，用于查找本地化字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TANK.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  为使用此强类型资源类的所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property add() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("add", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property blast() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("blast", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property blast1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blast1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blast2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blast2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blast3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blast3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blast4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blast4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blast5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blast5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blast6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blast6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blast7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blast7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property blast8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blast8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property bomb() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("bomb", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property born1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("born1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property born2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("born2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property born3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("born3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property born4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("born4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property destory() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("destory", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enemy1D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enemy1D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enemy1L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enemy1L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enemy1R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enemy1R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enemy1U() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enemy1U", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enemy2D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enemy2D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enemy2L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enemy2L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enemy2R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enemy2R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enemy2U() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enemy2U", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enemy3D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enemy3D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enemy3L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enemy3L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enemy3R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enemy3R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enemy3U() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enemy3U", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property enemymissile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("enemymissile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property fire() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("fire", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property grass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property hit() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("hit", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property mintank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mintank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property over() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("over", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property p1tankD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p1tankD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property p1tankL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p1tankL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property p1tankR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p1tankR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property p1tankU() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p1tankU", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property p2tankD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p2tankD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property p2tankL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p2tankL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property p2tankR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p2tankR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property p2tankU() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p2tankU", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property select1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("select1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property selecttank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("selecttank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property snow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("snow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property star() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("star", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property start() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("start", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property steel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("steel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property steels() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("steels", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property symbol() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("symbol", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property tankmissile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tankmissile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property timer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("timer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property title() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("title", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property wall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property walls() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("walls", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property water() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("water", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
